class Exception(Exception):
    def __init__(self, code):
        super().__init__()
        self.code = code
    def __str__(self):
        return str(self.code)

    CLIP__NOT_EXIST = "CLIP__NOT_EXIST"
    CLIP__ALREADY_CREATED = "CLIP__ALREADY_CREATED"

    CLIP_SEGMENTS__NOT_EXIST = "CLIP_SEGMENTS__NOT_EXIST"

    CLIPS__NOT_EXIST = "CLIPS__NOT_EXIST"
    CLIPS__NOT_CREATED = "CLIPS__NOT_CREATED"

    MEDIA__NOT_EXIST = "MEDIA__NOT_EXIST"

    MONTAGE__NOT_EXIST = "MONTAGE__NOT_EXIST"
    MONTAGE__ALREADY_CREATED = "MONTAGE__ALREADY_CREATED"

    MONTAGE_CLIPS__NOT_EXIST = "MONTAGE_CLIPS__NOT_EXIST"

    STREAM__NOT_EXIST = "STREAM__NOT_EXIST"
    STREAM__NOT_ANALYZED = "STREAM__NOT_ANALYZED"
    STREAM__NOT_INITIALIZED = "STREAM__NOT_INITIALIZED"
    STREAM__ALREADY_ANALYZED = "STREAM__ALREADY_ANALYZED"
    STREAM__ALREADY_INITIALIZED = "STREAM__ALREADY_INITIALIZED"

    STREAM_ID__NOT_VALID = "STREAM_ID__NOT_VALID"

    STREAM_SEGMENT__NOT_EXIST = "STREAM_SEGMENT__NOT_EXIST"
    STREAM_SEGMENT__NOT_DOWNLOADED = "STREAM_SEGMENT__NOT_DOWNLOADED"
    STREAM_SEGMENT__ALREADY_DOWNLOADED = "STREAM_SEGMENT__ALREADY_DOWNLOADED"
    STREAM_SEGMENT__ALREADY_ANALYZED = "STREAM_SEGMENT__ALREADY_ANALYZED"

    STREAM_SEGMENTS__NOT_EXIST = "STREAM_SEGMENTS__NOT_EXIST"
    STREAM_SEGMENTS__NOT_DOWNLOADED = "STREAM_SEGMENTS__NOT_DOWNLOADED"

    STREAM_MOMENTS__NOT_EXIST = "STREAM_MOMENTS__NOT_EXIST"

