class Exception(Exception):
    def __init__(self, code):
        super().__init__()
        self.code = code
    def __str__(self):
        return str(self.code)

    CLIP__ALREADY_PROCESSED = "CLIP__ALREADY_PROCESSED"
    CLIP__CLIP_SEGMENTS_NOT_EXIST = "CLIP__CLIP_SEGMENTS_NOT_EXIST"
    CLIP__NOT_EXIST = "CLIP__NOT_EXIST"
    CLIP__STREAM_SEGMENTS_NOT_EXIST = "CLIP__STREAM_SEGMENTS_NOT_EXIST"

    CLIPS__NOT_EXIST = "CLIPS__NOT_EXIST"
    CLIPS__NOT_READY = "CLIPS__NOT_READY"

    STREAM__ALREADY_PROCESSED = "STREAM__ALREADY_PROCESSED"
    STREAM__NOT_EXIST = "STREAM__NOT_EXIST"
    STREAM__NOT_READY = "STREAM__NOT_READY"

    STREAM_ID__INVALID = "STREAM_ID__INVALID"

    STREAM_SEGMENT__ALREADY_PROCESSED = "STREAM_SEGMENT__ALREADY_PROCESSED"
    STREAM_SEGMENT__NOT_EXIST = "STREAM_SEGMENT__NOT_EXIST"
    STREAM_SEGMENT__NOT_INITIALIZING = "STREAM_SEGMENT__NOT_INITIALIZING"

    STREAM_SEGMENTS__NOT_EXIST = "STREAM_SEGMENTS__NOT_EXIST"
    STREAM_SEGMENTS__NOT_READY = "STREAM_SEGMENTS__NOT_READY"

    MEDIA_EXPORT__ALREADY_PROCESSED = "MEDIA_EXPORT__ALREADY_PROCESSED"
    MEDIA_EXPORT__ALREADY_INITIALIZING = "MEDIA_EXPORT__ALREADY_INITIALIZING"
    MEDIA_EXPORT__INVALID_MEDIA_TYPE = "MEDIA_EXPORT__INVALID_MEDIA_TYPE"

    MONTAGE__NOT_EXIST = "MONTAGE__NOT_EXIST"
    MONTAGE_CLIPS__NOT_EXIST = "MONTAGE_CLIPS__NOT_EXIST"
