log:
  level: INFO

aws:
  account-id: 589344262905
  region: us-west-1

  dynamodb:
    streams:
      name: ts-streams
    stream-segments:
      name: ts-stream-segments
    clips:
      name: ts-clips
    clip-segments:
      name: ts-clip-segments
    montages:
      name: ts-montages
    montage-clips:
      name: ts-montage-clips

  iam:
    role-statement:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
        Resource: arn:aws:dynamodb:us-west-1:589344262905:*
      - Effect: Allow
        Action:
          - iam:PassRole
        Resource: arn:aws:iam::589344262905:*
      - Effect: Allow
        Action:
          - mediaconvert:CreateJob
        Resource: arn:aws:mediaconvert:us-west-1:589344262905:*
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: arn:aws:s3:::*
      - Effect: Allow
        Action:
          - sqs:GetQueueUrl
          - sqs:SendMessage
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:ChangeMessageVisibility
        Resource: arn:aws:sqs:us-west-1:589344262905:*

  mediaconvert:
    role: arn:aws:iam::589344262905:role/ServiceRoleForMediaConvert
    url: https://2atsycqh.mediaconvert.us-west-1.amazonaws.com
    clip: arn:aws:mediaconvert:us-west-1:589344262905:queues/Clip
    montage: arn:aws:mediaconvert:us-west-1:589344262905:queues/Montage

  s3:
    main:
      name: twitch-stitch-main
      region: us-west-1
    exported:
      name: twitch-stitch-exported
    thumbnails:
      name: twitch-stitch-thumbnails

  sqs:
    clip:
      name: ts-clip
    montage:
      name: ts-montage
    stream--analyze:
      name: ts-stream--analyze
    stream--initialize:
      name: ts-stream--initialize
    stream-segment--analyze:
      name: ts-stream-segment--analyze
    stream-segment--download:
      name: ts-stream-segment--download
