account-id: 589344262905
log-level: INFO
region: us-east-2
stage: dev

cognito:
  pool-id: us-east-2_N2uwzTRn4

rds:
  db: twitchstitch
  username: twitchstitch
  password: u4zSe2UafzM0
  host: cluster-cf5c9fucgqvd.us-east-2.rds.amazonaws.com
  class: db.r4.large

iam:
  role-statement:
    - Effect: Allow
      Action:
        - mediaconvert:CreateJob
      Resource: arn:aws:mediaconvert:us-east-2:589344262905:*
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::*
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:ChangeMessageVisibility
      Resource: arn:aws:sqs:us-east-2:589344262905:*

mediaconvert:
  role: arn:aws:iam::589344262905:role/ServiceRoleForMediaConvert
  url: https://kl6yojlz.mediaconvert.us-east-2.amazonaws.com
  queues:
    clip:
      arn: arn:aws:mediaconvert:us-east-2:589344262905:queues/clip
    montage:
      arn: arn:aws:mediaconvert:us-east-2:589344262905:queues/montage

s3:
  buckets:
    media:
      name: twitch-stitch-media

sqs:
  queues:
    clip:
      name: ts-clip
    montage:
      name: ts-montage
    stream--analyze:
      name: ts-stream--analyze
    stream--initialize:
      name: ts-stream--initialize
    stream-segment--analyze:
      name: ts-stream-segment--analyze
    stream-segment--download:
      name: ts-stream-segment--download
