account-id: 923755341410
log-level: INFO
region: us-west-2
stage: prod

rds:
  db: twitchstitch
  username: twitchstitch
  password: 21HzJVvwLvsi
  host: ts-prod.c3ffqlddkpmv.us-west-2.rds.amazonaws.com

iam:
  role-statement:
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:ChangeMessageVisibility
      Resource: arn:aws:sqs:us-west-2:923755341410:*
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::*
    - Effect: Allow
      Action:
        - mediaconvert:CreateJob
      Resource: arn:aws:mediaconvert:us-west-2:923755341410:*
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: arn:aws:iam::923755341410:*

lambda:
  layers:
    tesseract:
      arn: arn:aws:lambda:us-west-2:923755341410:layer:ts-layers-prod-layer--ffmpeg:8
    ffmpeg:
      arn: arn:aws:lambda:us-west-2:923755341410:layer:ts-layers-prod-layer--tesseract:8

mediaconvert:
  role: arn:aws:iam::923755341410:role/ServiceRoleForMediaConvert
  url: https://zlxmu0qla.mediaconvert.us-west-2.amazonaws.com
  queues:
    clip:
      arn: arn:aws:mediaconvert:us-west-2:923755341410:queues/clip-prod
    montage:
      arn: arn:aws:mediaconvert:us-west-2:923755341410:queues/montage-prod

s3:
  buckets:
    media:
      name: ts-media-prod

sqs:
  queues:
    clip:
      name: ts-clip---prod
    montage:
      name: ts-montage---prod
    stream--analyze:
      name: ts-stream--analyze---prod
    stream--initialize:
      name: ts-stream--initialize---prod
    stream-segment--analyze:
      name: ts-stream-segment--analyze---prod
    stream-segment--download:
      name: ts-stream-segment--download---prod
