log:
  level: INFO

aws:
  account-id: 589344262905
  dynamodb:
    streams:
      name: ts-streams
    stream-segments:
      name: ts-stream-segments
    clips:
      name: ts-clips
    clip-segments:
      name: ts-clip-segments
    montages:
      name: ts-montages
    montage-clips:
      name: ts-montage-clips
  s3:
    main:
      name: twitch-stitch-main
      region: us-west-1
    exported:
      name: twitch-stitch-exported
    thumbnails:
      name: twitch-stitch-thumbnails
  sqs:
    clip:
      name: ts-clip
    stream-initialize:
      name: ts-stream-initialize
    stream-segment-download:
      name: ts-stream-segment-download

