account-id: 923755341410
log-level: INFO
region: us-east-1
stage: dev

rds:
  db: twitchstitch
  username: twitchstitch
  password: u4zSe2UafzM0
  host: ts-dev.cedt61aecxoc.us-east-1.rds.amazonaws.com

iam:
  role-statement:
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:ChangeMessageVisibility
      Resource: arn:aws:sqs:us-east-1:923755341410:*
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::*
    - Effect: Allow
      Action:
        - mediaconvert:CreateJob
      Resource: arn:aws:mediaconvert:us-east-1:923755341410:*
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: arn:aws:iam::923755341410:*

lambda:
  layers:
    tesseract:
      arn: arn:aws:lambda:us-west-2:923755341410:layer:ts-layers-prod-layer--tesseract:1
    ffmpeg:
      arn: arn:aws:lambda:us-west-2:923755341410:layer:ts-layers-prod-layer--ffmpeg:1

mediaconvert:
  role: arn:aws:iam::923755341410:role/ServiceRoleForMediaConvert
  url: https://5uowyzvia.mediaconvert.us-east-1.amazonaws.com
  queues:
    clip:
      arn: arn:aws:mediaconvert:us-east-1:923755341410:queues/clip-dev
    montage:
      arn: arn:aws:mediaconvert:us-east-1:923755341410:queues/montage-dev

s3:
  buckets:
    media:
      name: ts-media-dev

sqs:
  queues:
    clip:
      name: ts-clip---dev
    montage:
      name: ts-montage---dev
    stream--analyze:
      name: ts-stream--analyze---dev
    stream--initialize:
      name: ts-stream--initialize---dev
    stream-segment--analyze:
      name: ts-stream-segment--analyze---dev
    stream-segment--download:
      name: ts-stream-segment--download---dev
